ProjectDisplayName = JSON Well Log Format

JavaPackages = \
        no/geosoft/jwlf \

JavaLibraries = \
	javax.json-1.1.3.jar \
	javax.json-api-1.1.3.jar \
	justify-0.15.0.jar \

include $(DEV_HOME)/tools/Make/Makefile
