Source = \
	JsonCurve.java \
	JsonDataListener.java \
	JsonLog.java \
	JsonLogUtil.java \
	JsonReader.java \
	JsonTable.java \
	JsonUtil.java \
	JsonValidator.java \
	JsonValueType.java \
	JsonWellLogFormatSchema.java \
	JsonWellLogProperty.java \
	JsonWriter.java \
	units.txt \

Main = JsonReader

include $(DEV_HOME)/JSONWellLogFormat/Java/Makefile