Source = \
	DataArray.java \
	DoubleList.java \
	FloatList.java \
	Formatter.java \
	Indentation.java \
	IntList.java \
	ISO8601DateParser.java \
	JsonCurve.java \
	JsonDataListener.java \
	JsonLog.java \
	JsonReader.java \
	JsonTable.java \
	JsonUtil.java \
	JsonValidator.java \
	JsonValueType.java \
	JsonWellLogFormatSchema.java \
	JsonWellLogProperty.java \
	JsonWriter.java \
	Util.java \
	units.txt \

include $(DEV_HOME)/JSONWellLogFormat/Java/Makefile